In [1]:
import cv2
import os
import sys

import numpy as np
import matplotlib.pyplot as plt

In [2]:
root1 = 'data/'
root2 = 'data_pre_processing/'
TRAIN_PATH = 'stage1_train/'
TEST_PATH = 'stage1_test/'

In [3]:
# Get train and test IDs
train_ids = next(os.walk(root1+TRAIN_PATH))[1]
test_ids = next(os.walk(root1+TEST_PATH))[1]
print (len(train_ids))
print (len(test_ids))


670
65


In [4]:
sum1= np.zeros(3)
sum2= np.zeros(3) 
for n, id_ in enumerate(train_ids):
    path = root1 + TRAIN_PATH + id_
    img = cv2.imread(path + '/images/' + id_ + '.png')
    img = img.astype(float)/255
    mean_b = np.mean(img[:,:,0])
    mean_g = np.mean(img[:,:,1])
    mean_r = np.mean(img[:,:,2])

    std_b = np.std(img[:,:,0])
    std_g = np.std(img[:,:,1])
    std_r = np.std(img[:,:,2])

    mean_rgb=np.array([mean_r,mean_g,mean_b])
    std_rgb=np.array([std_r,std_g,std_b])    
    sum1=sum1+ mean_rgb
    sum2=sum2+ std_rgb
    
mean_rgb_train=sum1/len(train_ids)
std_rgb_train=sum2/len(train_ids)

print (mean_rgb_train,std_rgb_train)

[ 0.17071716  0.15513969  0.18911588] [ 0.06676521  0.07642292  0.05697663]


In [5]:
sum1= np.zeros(3)
sum2= np.zeros(3) 
for n, id_ in enumerate(test_ids):
    path = root1 + TEST_PATH + id_
    img = cv2.imread(path + '/images/' + id_ + '.png')
    img = img.astype(float)/255
    mean_b = np.mean(img[:,:,0])
    mean_g = np.mean(img[:,:,1])
    mean_r = np.mean(img[:,:,2])

    std_b = np.std(img[:,:,0])
    std_g = np.std(img[:,:,1])
    std_r = np.std(img[:,:,2])

    mean_rgb=np.array([mean_r,mean_g,mean_b])
    std_rgb=np.array([std_r,std_g,std_b])    
    sum1=sum1+ mean_rgb
    sum2=sum2+ std_rgb
    
mean_rgb_test=sum1/len(test_ids)
std_rgb_test=sum2/len(test_ids)

print (mean_rgb_test,std_rgb_test)

[ 0.21683351  0.20622558  0.20976349] [ 0.10790828  0.11459805  0.09966981]


In [6]:
mean_=0.5*(mean_rgb_train+mean_rgb_test)
std_=0.5*(std_rgb_train+ std_rgb_test)
mean_,std_

(array([ 0.19377533,  0.18068263,  0.19943969]),
 array([ 0.08733674,  0.09551049,  0.07832322]))